/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wangw_samples_jni_NativeMethods */

#ifndef _Included_com_wangw_samples_jni_NativeMethods
#define _Included_com_wangw_samples_jni_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wangw_samples_jni_NativeMethods
 * Method:    hellowWord
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wangw_samples_jni_NativeMethods_hellowWord
  (JNIEnv *, jclass);

/*
 * Class:     com_wangw_samples_jni_NativeMethods
 * Method:    hellowWord2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wangw_samples_jni_NativeMethods_hellowWord2
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
